In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('D:/.vscode/Python-2026-L1/students.csv')
df2 = pd.read_csv('D:/.vscode/Python-2026-L1/scores.csv')

In [3]:
df.head()

  student_id   name   age          major   GPA
0       S001  Alice  20.0            ICT  3.40
1       S002    Bob  21.0   Data Science  3.70
2       S003  Carol  20.0            ICT  3.20
3       S004  David  22.0   Data Science  3.80
4       S005   Emma  21.0  Cybersecurity  3.55

In [5]:
df.shape

(30, 5)

In [7]:
df[["name", "GPA"]]

      name   GPA
0    Alice  3.40
1      Bob  3.70
2    Carol  3.20
3    David  3.80
4     Emma  3.55
5    Frank  3.10
6    Grace  3.85
7    Henry  2.95
8      Ivy  3.60
9     Jack  3.35
10    Kate  3.90
11     Leo   NaN
12     Mia  3.45
13    Noah  3.75
14  Olivia  3.50
15   Peter  3.15
16   Quinn  3.65
17    Rose  3.05
18     Sam  3.30
19    Tina  3.95
20     Uma  3.25
21  Victor  3.55
22   Wendy  3.70
23  Xavier  3.40
24    Yara   NaN
25    Zack  3.80
26    Anna  3.60
27   Brian  2.85
28   Chloe  3.90
29  Daniel  3.45

In [8]:
df[df["GPA"] >= 3.5]

   student_id    name   age                major   GPA
1        S002     Bob  21.0         Data Science  3.70
3        S004   David  22.0         Data Science  3.80
4        S005    Emma  21.0        Cybersecurity  3.55
6        S007   Grace  21.0                  ICT  3.85
8        S009     Ivy  20.0         Data Science  3.60
10       S011    Kate  22.0                  ICT  3.90
13       S014    Noah  22.0  Applied Mathematics  3.75
14       S015  Olivia   NaN                  ICT  3.50
16       S017   Quinn  20.0        Cybersecurity  3.65
19       S020    Tina  20.0         Data Science  3.95
21       S022  Victor  21.0  Applied Mathematics  3.55
22       S023   Wendy  20.0                  ICT  3.70
25       S026    Zack  20.0  Applied Mathematics  3.80
26       S027    Anna  21.0                  ICT  3.60
28       S029   Chloe  20.0        Cybersecurity  3.90

In [9]:
df.sort_values(by="GPA", ascending=False)

   student_id    name   age                major   GPA
19       S020    Tina  20.0         Data Science  3.95
10       S011    Kate  22.0                  ICT  3.90
28       S029   Chloe  20.0        Cybersecurity  3.90
6        S007   Grace  21.0                  ICT  3.85
3        S004   David  22.0         Data Science  3.80
25       S026    Zack  20.0  Applied Mathematics  3.80
13       S014    Noah  22.0  Applied Mathematics  3.75
22       S023   Wendy  20.0                  ICT  3.70
1        S002     Bob  21.0         Data Science  3.70
16       S017   Quinn  20.0        Cybersecurity  3.65
8        S009     Ivy  20.0         Data Science  3.60
26       S027    Anna  21.0                  ICT  3.60
4        S005    Emma  21.0        Cybersecurity  3.55
21       S022  Victor  21.0  Applied Mathematics  3.55
14       S015  Olivia   NaN                  ICT  3.50
29       S030  Daniel  21.0  Applied Mathematics  3.45
12       S013     Mia  21.0        Cybersecurity  3.45
0        S001   Alice  20.0                  ICT  3.40
23       S024  Xavier  22.0         Data Science  3.40
9        S010    Jack  21.0  Applied Mathematics  3.35
18       S019     Sam  21.0                  ICT  3.30
20       S021     Uma  22.0        Cybersecurity  3.25
2        S003   Carol  20.0                  ICT  3.20
15       S016   Peter  21.0         Data Science  3.15
5        S006   Frank  20.0  Applied Mathematics  3.10
17       S018    Rose  22.0  Applied Mathematics  3.05
7        S008   Henry  22.0        Cybersecurity  2.95
27       S028   Brian  22.0         Data Science  2.85
11       S012     Leo  20.0         Data Science   NaN
24       S025    Yara  21.0        Cybersecurity   NaN

In [11]:
df.groupby("major")["GPA"].mean()

major
Applied Mathematics    3.435714
Cybersecurity          3.458333
Data Science           3.492857
ICT                    3.556250
Name: GPA, dtype: float64

In [17]:
df2.isnull().sum()
df2.dropna(inplace=True)

In [18]:
df3 = pd.merge(df, df2, on="student_id", how="inner")

In [19]:
df3.head()

  student_id   name   age          major   GPA  python  math  database
0       S001  Alice  20.0            ICT  3.40      85  80.0      88.0
1       S002    Bob  21.0   Data Science  3.70      92  88.0      90.0
2       S003  Carol  20.0            ICT  3.20      78  82.0      76.0
3       S004  David  22.0   Data Science  3.80      95  91.0      94.0
4       S005   Emma  21.0  Cybersecurity  3.55      89  84.0      91.0

In [25]:
df3['Average'] = df3[['python', 'math', 'database']].mean(axis=1)
print(df3[['name', 'Average']])

      name    Average
0    Alice  84.333333
1      Bob  90.000000
2    Carol  78.666667
3    David  93.333333
4     Emma  88.000000
5    Frank  77.333333
6    Grace  93.000000
7    Henry  71.000000
8      Ivy  89.000000
9     Jack  84.666667
10    Kate  95.000000
11     Mia  87.000000
12    Noah  90.333333
13  Olivia  83.333333
14   Peter  79.333333
15   Quinn  90.000000
16    Rose  78.000000
17     Sam  80.000000
18    Tina  96.333333
19     Uma  79.666667
20  Victor  87.000000
21   Wendy  89.666667
22    Yara  82.333333
23    Zack  92.333333
24    Anna  89.000000
25   Brian  71.333333
26  Daniel  85.333333

In [26]:
df3.nlargest(5, 'Average')[['name', 'Average']]

     name    Average
18   Tina  96.333333
10   Kate  95.000000
3   David  93.333333
6   Grace  93.000000
23   Zack  92.333333

In [27]:
df3.groupby("major")["Average"].mean()

major
Applied Mathematics    85.000000
Cybersecurity          83.000000
Data Science           86.555556
ICT                    86.625000
Name: Average, dtype: float64